language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - composer install --prefer-source

script: phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
